function [fitresult, gof] = createFit(flCurveFiberLength, flCurveFiberActiveforce)
%CREATEFIT(FLCURVEFIBERLENGTH,FLCURVEFIBERACTIVEFORCE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : flCurveFiberLength
%      Y Output: flCurveFiberActiveforce
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Aug-2014 16:45:51


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( flCurveFiberLength, flCurveFiberActiveforce );

% Set up fittype and options.
ft = fittype( 'splineinterp' );
opts = fitoptions( ft );
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

%Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult,'k');
% 
% h = plot( fitresult, xData, yData );
% legend( h, 'flCurveFiberActiveforce vs. flCurveFiberLength', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'flCurveFiberLength' );
% ylabel( 'flCurveFiberActiveforce' );
% grid on


