function [storage] = musclePropList(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [ADDBREV_R,VARNAME2,VARNAME3,VARNAME4,VARNAME5] = IMPORTFILE(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   [ADDBREV_R,VARNAME2,VARNAME3,VARNAME4,VARNAME5] = IMPORTFILE(FILENAME,
%   STARTROW, ENDROW) Reads data from rows STARTROW through ENDROW of text
%   file FILENAME.
%
% Example:
%   [addbrev_r,VarName2,VarName3,VarName4,VarName5] =
%   importfile('musclePropertyList.txt',1, 40);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/01/27 17:57:53

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
addbrev_r = dataArray{:, 1};
VarName2 = dataArray{:, 2};
VarName3 = dataArray{:, 3};
VarName4 = dataArray{:, 4};
VarName5 = dataArray{:, 5};




for i = 1 : length(addbrev_r)
        storage.(addbrev_r{i}) = [VarName2(i) VarName3(i) VarName4(i) VarName5(i)];
    
    
    
end













